# Generated by Django 4.1.2 on 2022-10-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='')),
                ('title', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('photos', models.CharField(max_length=50)),
                ('event_starts', models.CharField(max_length=10)),
                ('event_ends', models.CharField(max_length=10)),
                ('created_at', models.CharField(max_length=10)),
                ('updated_at', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
